### ISSUE TITLE
我的项目不能引用AbstractProcess

### ISSUE THREAD

**Issue by menshen** [lilongweidev/StudyAnnotation#1]
运行报错：
错误: 找不到符号
符号: 类 AbstractProcess
我创建的module也是javalib。

**Comment by lilongweidev** [comment]
你添加依赖库了吗

**Comment by menshen** [comment]
都添加了，最后我用IDEA把apt的代码写完，然后导入到android studio上。
android studio不能识别Apt相关的引用，但是可以正常运行。
我正常定义一个注解在android library module上没问题，但是在java library module上就有引用的问题，可以正常编译，但是android studio ide不能之别那些类，比如@Target 等。

**Comment by lilongweidev** [comment]
你直接用Android Studio写，为啥要用IDEA






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月25日(星期二) 晚上11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [lilongweidev/StudyAnnotation] 我的项目不能引用AbstractProcess (Issue #1)





 
都添加了，最后我用IDEA把apt的代码写完，然后导入到android studio上。
 android studio不能识别Apt相关的引用，但是可以正常运行。
 我正常定义一个注解在android library module上没问题，但是在java library module上就有引用的问题，可以正常编译，但是android studio ***@***.*** 等。

**Comment by menshen** [comment]
因为android studio引用不到apt相关的类。
解释下：
可以编译过
但是ide的编辑器里会报红的那种。（编辑器里，红色的。Can't resolve symbol ***那种）
不知道我的解释你是否能明白。挺饶舌的。
